"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        "dashboard": "Dashboard",
        "residents": "Residents",
        "business_analytics": "Business Analytics",
        "demographics": "Demographics",
        "ai_insights": "AI Insights",
        "whatsapp": "WhatsApp",
        "settings": "Settings",
        "system_online": "System Online",
        "admin_access": "Admin Access",
        "recent_activity": "Recent Activity",
        "revenue_trend": "Revenue Trend",
        "total_citizens": "Total Citizens",
        "total_tourists": "Total Tourists",
        "active_businesses": "Active Businesses",
        "growth": "Growth",
        "good_morning": "Good Morning",
        "good_afternoon": "Good Afternoon",
        "good_evening": "Good Evening",
        "lanzarote_town_hall": "Lanzarote Town Hall",
        "search": "Search...",
        "all_systems_operational": "All Systems Operational",
        "mayor": "Mayor",
        "admin": "Admin",
        "recent_actions": "Latest actions & events",
        "revenue_description": "Monthly municipal revenue (past 12m)",
        "citizen_records": "Citizen Records",
        "view_demographics": "View demographics & records",
        "revenue_insights": "Revenue & sector insights",
        "population_data": "Population & age data",
        "ask_questions": "Ask questions about city data",
        "census_registered": "census registered",
        "registered_entities": "registered entities",
        "municipal_estimate": "municipal estimate",
        "by_air_cruise": "by air & cruise",
        "menu": "Menu",
        "ai_assistant": "AI Assistant",
        "type_message": "Type message...",
        "ask_something": "Ask about Lanzarote",
        "municipalities": "Municipalities",
        "satisfaction": "Satisfaction",
        "top_districts": "Top Municipalities",
        "performance": "Performance Overview",
        "quick_links": "Quick Links",
        "citizen_collection": "Citizen Collection",
        "sync_data": "Sync Data",
        "add_citizen": "Add Citizen",
        "total_records": "Total Records",
        "verified_citizens": "Verified Citizens",
        "new_registrations": "New Registrants",
        "pending_review": "Pending Review",
        "data_collection_progress": "Collection Progress",
        "district_collection_rate": "Rates by Town",
        "verification_status": "Verification Status",
        "export": "Export",
        "filter": "Filter",
        "all": "All",
        "verified": "Verified",
        "pending": "Pending",
        "unverified": "Unverified",
        "dob": "DOB",
        "contact": "Contact",
        "documents": "Documents",
        "status": "Status",
        "last_updated": "Updated",
        "intelligence": "Intelligence",
        "ask_anything": "Ask about city data...",
        "records_found": "records found",
        "search_placeholder": "Search name, ID, email, town…",
        "fully_verified": "Fully Verified",
        "partially_verified": "Partially Verified",
        "under_review": "Under Review",
        "ai_powered": "AI-Powered Insights",
        "try_now": "Try it now",
        "get_instant_answers": "Get instant answers about city data. Ask about demographics, revenue trends, or district comparisons.",
        "whatsapp_messenger": "WhatsApp Messenger",
        "whatsapp_desc": "Send targeted announcements and polls to citizens and businesses via WhatsApp",
        "select_audience": "Select Audience",
        "audience_desc": "Choose who will receive this message",
        "message_type": "Message Type",
        "message_type_desc": "Choose between a general announcement or an interactive poll",
        "schedule_send": "Schedule & Send",
        "schedule_desc": "Send immediately or schedule for later",
        "announcement": "Announcement",
        "announcement_desc": "One-way broadcast message",
        "poll_survey": "Poll / Survey",
        "poll_desc": "Interactive with response options",
        "template": "Template",
        "subject_title": "Subject / Title",
        "message_body": "Message Body",
        "poll_question": "Poll Question",
        "options": "Options",
        "add_option": "Add Option",
        "allow_multiple": "Allow multiple selections",
        "send_now": "Send Now",
        "schedule": "Schedule",
        "preview": "Preview",
        "send_message": "Send Message",
        "schedule_message": "Schedule Message",
        "message_sent": "Message Sent!",
        "sending": "Sending...",
        "audience_summary": "Audience Summary",
        "estimated_recipients": "estimated recipients",
        "delivery": "Delivery",
        "immediate": "Immediate",
        "scheduled": "Scheduled",
        "message_preview": "Message Preview",
        "recent_campaigns": "Recent Campaigns",
        "custom_message": "Custom Message",
        "scheduled_maintenance": "Scheduled Maintenance",
        "community_event": "Community Event",
        "policy_update": "Policy Update",
        "citizens_count": "3.3M total",
        "businesses_count": "48.4K total",
        "target_filters": "Target Filters",
        "no_filters": "No filters — sending to all",
        "filters_applied": "filters applied",
        "select_parameter": "Select parameter...",
        "select_value": "Select value...",
        "add": "Add",
        "age_group": "Age Group",
        "gender": "Gender",
        "sector": "Sector",
        "size": "Size",
        "business_analytics_title": "Business Analytics",
        "business_analytics_desc": "Track commercial activity, licensing, and economic performance across all districts",
        "total_businesses": "Total Businesses",
        "total_revenue": "Total Revenue",
        "active_licenses": "Active Licenses",
        "sector_breakdown": "Sector Breakdown",
        "sector_desc": "Businesses by industry sector",
        "revenue_by_district": "Revenue by District",
        "revenue_dist_desc": "Top 12 districts by annual revenue (€M)",
        "business_size": "Business Size",
        "by_employees": "By employee count",
        "business_directory": "Business Directory",
        "tourism_hospitality": "Tourism & Hospitality",
        "retail_commerce": "Retail & Commerce",
        "construction": "Construction",
        "agriculture_fishing": "Agriculture & Fishing",
        "technology_other": "Technology & Other",
        "food_hospitality": "Food & Hospitality",
        "tech_digital": "Technology & Digital",
        "healthcare_wellness": "Healthcare & Wellness",
        "construction_trade": "Construction & Trade",
        "professional_services": "Professional Services",
        "demographics_title": "Demographics",
        "demographics_desc": "Detailed breakdown of Lanzarote's population and resident statistics",
        "age_distribution": "Age Distribution",
        "age_desc": "Citizen breakdown by age group",
        "district_population": "District Population",
        "dist_pop_desc": "Top 12 of 21 districts by population",
        "gender_split": "Gender Split",
        "pop_by_gender": "Population by gender",
        "male": "Male",
        "female": "Female",
        "other_gender": "Other",
        "total_population": "Total Population",
        "residents_registered": "residents registered",
        "refresh": "Refresh",
        "export_csv": "Export CSV",
        "export_report": "Export Report",
        "micro": "Micro (1–5)",
        "small": "Small (6–25)",
        "medium": "Medium (26–100)",
        "large": "Large (100+)",
        "years": "years",
        "recipients": "recipients",
        "delivered": "delivered",
        "no_citizens_found": "No citizens found matching your search.",
        "no_businesses_found": "No businesses found matching your search.",
        "active": "Active",
        "inactive": "Inactive",
        "suspended": "Suspended",
        "jan": "Jan", "feb": "Feb", "mar": "Mar", "apr": "Apr", "may": "May", "jun": "Jun",
        "jul": "Jul", "aug": "Aug", "sep": "Sep", "oct": "Oct", "nov": "Nov", "dec": "Dec",
        "registered_users": "Registered Users",
        "vs_last_year": "vs last year",
        "vs_last_month": "vs last month",
        "vs_previous_month": "vs previous month",
        "full_coverage": "Full coverage",
        "annual_estimate": "annual estimate",
        "currently_valid": "currently valid",
        "this_quarter": "this quarter",
        "demographics_overview": "Citizen breakdown by age group",
        "annual_revenue_report": "Top 12 districts by annual revenue (€M)",
        "by_employee_count": "By employee count",
        "welcome_back": "Welcome back, Administrator",
    },
    es: {
        "dashboard": "Panel de Control",
        "residents": "Residentes",
        "business_analytics": "Análisis de Negocios",
        "demographics": "Demografía",
        "ai_insights": "Perspectivas IA",
        "whatsapp": "WhatsApp",
        "settings": "Ajustes",
        "system_online": "Sistema en Línea",
        "admin_access": "Acceso de Admin",
        "recent_activity": "Actividad Reciente",
        "revenue_trend": "Tendencia de Ingresos",
        "total_citizens": "Total de Ciudadanos",
        "total_tourists": "Total de Turistas",
        "active_businesses": "Negocios Activos",
        "growth": "Crecimiento",
        "good_morning": "Buenos Días",
        "good_afternoon": "Buenas Tardes",
        "good_evening": "Buenas Noches",
        "lanzarote_town_hall": "Ayuntamiento de Lanzarote",
        "search": "Buscar...",
        "all_systems_operational": "Sistemas Operativos",
        "mayor": "Alcalde",
        "admin": "Admin",
        "recent_actions": "Últimas acciones y eventos",
        "revenue_description": "Ingresos mensuales (12 meses)",
        "citizen_records": "Registros de Ciudadanos",
        "view_demographics": "Ver demografía y registros",
        "revenue_insights": "Ingresos y sectores",
        "population_data": "Población y edad",
        "ask_questions": "Preguntas de datos",
        "census_registered": "censo registrado",
        "registered_entities": "entidades registradas",
        "municipal_estimate": "estimación municipal",
        "by_air_cruise": "por aire y crucero",
        "menu": "Menú",
        "ai_assistant": "Asistente IA",
        "type_message": "Escriba mensaje...",
        "ask_something": "Preguntar sobre Lanzarote",
        "municipalities": "Municipios",
        "satisfaction": "Satisfacción",
        "top_districts": "Municipios Principales",
        "performance": "Resumen de Rendimiento",
        "quick_links": "Enlaces Rápidos",
        "citizen_collection": "Gestión de Ciudadanos",
        "sync_data": "Sincronizar",
        "add_citizen": "Nuevo Ciudadano",
        "total_records": "Total Registros",
        "verified_citizens": "Verificados",
        "new_registrations": "Nuevos Registros",
        "pending_review": "Pendiente de Revisión",
        "data_collection_progress": "Progreso de Datos",
        "district_collection_rate": "Tasa por Municipio",
        "verification_status": "Estado Verificación",
        "export": "Exportar",
        "filter": "Filtrar",
        "all": "Todos",
        "verified": "Verificados",
        "pending": "Pendientes",
        "unverified": "No Verificados",
        "dob": "F. Nacimiento",
        "contact": "Contacto",
        "documents": "Docs",
        "status": "Estado",
        "last_updated": "Actualizado",
        "intelligence": "Inteligencia",
        "ask_anything": "Pregunte sobre los datos...",
        "records_found": "registros encontrados",
        "search_placeholder": "Buscar nombre, ID, email, municipio…",
        "fully_verified": "Totalmente Verificado",
        "partially_verified": "Parcialmente Verificado",
        "under_review": "En Revisión",
        "ai_powered": "Perspectivas con Inteligencia Artificial",
        "try_now": "Pruébalo ahora",
        "get_instant_answers": "Obtenga respuestas al instante sobre los datos municipales. Pregunte sobre demografía, tendencias o comparaciones.",
        "whatsapp_messenger": "WhatsApp Messenger",
        "whatsapp_desc": "Envíe anuncios y encuestas dirigidas a ciudadanos y empresas por WhatsApp",
        "select_audience": "Seleccionar Audiencia",
        "audience_desc": "Elija quién recibirá este mensaje",
        "message_type": "Tipo de Mensaje",
        "message_type_desc": "Elija entre un anuncio general o una encuesta interactiva",
        "schedule_send": "Programar y Enviar",
        "schedule_desc": "Enviar de inmediato o programar para más tarde",
        "announcement": "Anuncio",
        "announcement_desc": "Mensaje de difusión unidireccional",
        "poll_survey": "Encuesta",
        "poll_desc": "Interactivo con opciones de respuesta",
        "template": "Plantilla",
        "subject_title": "Asunto / Título",
        "message_body": "Cuerpo del Mensaje",
        "poll_question": "Pregunta de la Encuesta",
        "options": "Opciones",
        "add_option": "Añadir Opción",
        "allow_multiple": "Permitir múltiples selecciones",
        "send_now": "Enviar Ahora",
        "schedule": "Programar",
        "preview": "Previsualizar",
        "send_message": "Enviar Mensaje",
        "schedule_message": "Programar Mensaje",
        "message_sent": "¡Mensaje Enviado!",
        "sending": "Enviando...",
        "audience_summary": "Resumen de Audiencia",
        "estimated_recipients": "destinatarios estimados",
        "delivery": "Entrega",
        "immediate": "Inmediata",
        "scheduled": "Programada",
        "message_preview": "Vista Previa del Mensaje",
        "recent_campaigns": "Campañas Recientes",
        "custom_message": "Mensaje Personalizado",
        "scheduled_maintenance": "Mantenimiento Programado",
        "community_event": "Evento Comunitario",
        "policy_update": "Actualización de Política",
        "citizens_count": "3.3M en total",
        "businesses_count": "48.4K en total",
        "target_filters": "Filtros de Objetivo",
        "no_filters": "Sin filtros — enviando a todos",
        "filters_applied": "filtros aplicados",
        "select_parameter": "Seleccionar parámetro...",
        "select_value": "Seleccionar valor...",
        "add": "Añadir",
        "age_group": "Grupo de Edad",
        "gender": "Género",
        "sector": "Sector",
        "size": "Tamaño",
        "business_analytics_title": "Análisis de Negocios",
        "business_analytics_desc": "Seguimiento de actividad comercial, licencias y rendimiento económico",
        "total_businesses": "Total de Empresas",
        "total_revenue": "Ingresos Totales",
        "active_licenses": "Licencias Activas",
        "sector_breakdown": "Desglose por Sector",
        "sector_desc": "Empresas por sector industrial",
        "revenue_by_district": "Ingresos por Municipio",
        "revenue_dist_desc": "Municipios principales por ingresos anuales (€M)",
        "business_size": "Tamaño de Empresa",
        "by_employees": "Por número de empleados",
        "business_directory": "Directorio de Empresas",
        "tourism_hospitality": "Turismo y Hostelería",
        "retail_commerce": "Comercio y Retail",
        "construction": "Construcción",
        "agriculture_fishing": "Agricultura y Pesca",
        "technology_other": "Tecnología y Otros",
        "food_hospitality": "Comida y Hostelería",
        "tech_digital": "Tecnología y Digital",
        "healthcare_wellness": "Salud y Bienestar",
        "construction_trade": "Construcción y Oficios",
        "professional_services": "Servicios Profesionales",
        "demographics_title": "Demografía",
        "demographics_desc": "Desglose detallado de la población de Lanzarote y estadísticas de residentes",
        "age_distribution": "Distribución por Edad",
        "age_desc": "Desglose de ciudadanos por grupo de edad",
        "district_population": "Población por Municipio",
        "dist_pop_desc": "Municipios principales por población",
        "gender_split": "División por Género",
        "pop_by_gender": "Población por género",
        "male": "Hombre",
        "female": "Mujer",
        "other_gender": "Otro",
        "total_population": "Población Total",
        "residents_registered": "residentes registrados",
        "refresh": "Actualizar",
        "export_csv": "Exportar CSV",
        "export_report": "Exportar Informe",
        "micro": "Micro (1–5)",
        "small": "Pequeña (6–25)",
        "medium": "Mediana (26–100)",
        "large": "Grande (100+)",
        "years": "años",
        "recipients": "destinatarios",
        "delivered": "entregado",
        "no_citizens_found": "No se encontraron ciudadanos coincidentes.",
        "jan": "Ene", "feb": "Feb", "mar": "Mar", "apr": "Abr", "may": "May", "jun": "Jun",
        "jul": "Jul", "aug": "Ago", "sep": "Sep", "oct": "Oct", "nov": "Nov", "dec": "Dic",
        "registered_users": "Usuarios Registrados",
        "vs_last_year": "vs año pasado",
        "vs_last_month": "vs mes pasado",
        "vs_previous_month": "vs mes anterior",
        "full_coverage": "Cobertura total",
        "annual_estimate": "estimación anual",
        "currently_valid": "actualmente válido",
        "this_quarter": "este trimestre",
        "demographics_overview": "Desglose de ciudadanos por grupo de edad",
        "annual_revenue_report": "Municipios principales por ingresos anuales (€M)",
        "by_employee_count": "Por número de empleados",
        "welcome_back": "Bienvenido de nuevo, Administrador",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>("en");

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
